<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>873f4c77-8286-491e-9251-71be9d0d6a17</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.6"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.3" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Npgsql" Version="9.0.3" />
        <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0"/>
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WalletMate.BLL.Shared\WalletMate.BLL.Shared.csproj" />
      <ProjectReference Include="..\WalletMate.DAL.Context\WalletMate.DAL.Context.csproj" />
      <ProjectReference Include="..\WalletMate.DAL.Migrations\WalletMate.DAL.Migrations.csproj" />
    </ItemGroup>

</Project>
