<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>52dba97f-22b9-4eee-85a2-d7646586ce1d</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.14" />
        <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.6" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.3">
          <PrivateAssets>all</PrivateAssets>
          <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="9.0.3" />
        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="9.0.3" />
        <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
        <PackageReference Include="Swashbuckle.AspNetCore" Version="6.4.0" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\WalletMate.Adapters.Out.Cache\WalletMate.Adapters.Out.Cache.csproj" />
      <ProjectReference Include="..\WalletMate.Adapters.Out.Database.Migrations\WalletMate.Adapters.Out.Database.Migrations.csproj" />
      <ProjectReference Include="..\WalletMate.Adapters.Out.Database\WalletMate.Adapters.Out.Database.csproj" />
      <ProjectReference Include="..\WalletMate.Adapters.Out.Monobank\WalletMate.Adapters.Out.Monobank.csproj" />
      <ProjectReference Include="..\WalletMate.Adapters.Out.Shared.Http\WalletMate.Adapters.Out.Shared.Http.csproj" />
      <ProjectReference Include="..\WalletMate.Application\WalletMate.Application.csproj" />
    </ItemGroup>

</Project>
